inherit_gem:
  rubocop-github:
    - config/default_edge.yml
    - config/rails_edge.yml

AllCops:
  NewCops: enable
  SuggestExtensions: false

Rails/RefuteMethods:
  Enabled: false

Style/Documentation:
  Enabled: false

Rails/RakeEnvironment:
  Enabled: false